#pragma once

// *** AUTO-GENERATED — do not edit by hand ***
// Regenerate with:  python tools/generate_station_names.py
//
// Sorted lookup table: LED strip index → station name.
// Used by the TEST / TRACKINFO / WHICH / REPORT serial commands.

#include <stdint.h>

struct StationNameEntry {
    uint16_t led;
    const char *constName;  // C constant name, e.g. WEST_RUISLIP
    const char *humanName;  // readable name, e.g. "West Ruislip"
};

static const StationNameEntry kStationNames[] = {
    {   0, "HEATHROW_TERMINAL_4_A", "Heathrow Terminal 4 (A)"},
    {   1, "HEATHROW_TERMINAL_4_B", "Heathrow Terminal 4 (B)"},
    {   2, "HEATHROW_TERMINAL_5_A", "Heathrow Terminal 5 (A)"},
    {   3, "HEATHROW_TERMINAL_5_B", "Heathrow Terminal 5 (B)"},
    {   4, "HEATHROW_TERMINALS_2_3_A", "Heathrow Terminals 2 3 (A)"},
    {   5, "HEATHROW_TERMINALS_2_3_B", "Heathrow Terminals 2 3 (B)"},
    {   6, "HATTON_CROSS", "Hatton Cross"},
    {   7, "HOUNSLOW_WEST", "Hounslow West"},
    {   8, "HOUNSLOW_CENTRAL", "Hounslow Central"},
    {   9, "HOUNSLOW_EAST", "Hounslow East"},
    {  10, "BOSTON_MANOR", "Boston Manor"},
    {  11, "NORTHFIELDS", "Northfields"},
    {  12, "SOUTH_EALING", "South Ealing"},
    {  13, "ACTON_TOWN_A", "Acton Town (A)"},
    {  14, "EALING_COMMON", "Ealing Common"},
    {  15, "EALING_BROADWAY", "Ealing Broadway"},
    {  18, "WEST_EALING", "West Ealing"},
    {  19, "HANWELL", "Hanwell"},
    {  20, "SOUTHALL", "Southall"},
    {  21, "HAYES_HARLINGTON", "Hayes Harlington"},
    {  22, "WEST_DRAYTON", "West Drayton"},
    {  23, "LANGLEY", "Langley"},
    {  25, "SLOUGH", "Slough"},
    {  26, "BURNHAM", "Burnham"},
    {  27, "TAPLOW", "Taplow"},
    {  29, "TWYFORD", "Twyford"},
    {  30, "READING", "Reading"},
    {  31, "UXBRIDGE", "Uxbridge"},
    {  32, "HILLINGDON", "Hillingdon"},
    {  33, "ICKENHAM", "Ickenham"},
    {  34, "WEST_RUISLIP", "West Ruislip"},
    {  35, "AMERSHAM", "Amersham"},
    {  36, "CHESHAM", "Chesham"},
    {  37, "CHALFONT_LATIMER", "Chalfont Latimer"},
    {  38, "CHORLEYWOOD", "Chorleywood"},
    {  39, "WATFORD", "Watford"},
    {  40, "CROXLEY", "Croxley"},
    {  41, "RICKMANSWORTH", "Rickmansworth"},
    {  42, "MOOR_PARK", "Moor Park"},
    {  43, "NORTHWOOD", "Northwood"},
    {  44, "NORTHWOOD_HILLS", "Northwood Hills"},
    {  45, "PINNER", "Pinner"},
    {  46, "NORTH_HARROW", "North Harrow"},
    {  47, "HARROW_ON_THE_HILL", "Harrow On the Hill"},
    {  48, "WEST_HARROW", "West Harrow"},
    {  49, "RAYNERS_LANE", "Rayners Lane"},
    {  50, "RUISLIP_MANOR", "Ruislip Manor"},
    {  51, "RUISLIP", "Ruislip"},
    {  52, "RUISLIP_GARDENS", "Ruislip Gardens"},
    {  53, "SOUTH_RUISLIP", "South Ruislip"},
    {  54, "NORTHOLT", "Northolt"},
    {  55, "GREENFORD", "Greenford"},
    {  56, "PERIVALE", "Perivale"},
    {  57, "HANGER_LANE", "Hanger Lane"},
    {  58, "PARK_ROYAL", "Park Royal"},
    {  59, "NORTH_EALING", "North Ealing"},
    {  60, "ACTON_MAIN_LINE", "Acton Main Line"},
    {  61, "WEST_ACTON", "West Acton"},
    {  62, "ACTON_CENTRAL", "Acton Central"},
    {  63, "SOUTH_ACTON", "South Acton"},
    {  64, "ACTON_TOWN_B", "Acton Town (B)"},
    {  65, "ACTON_TOWN_C", "Acton Town (C)"},
    {  66, "CHISWICK_PARK", "Chiswick Park"},
    {  67, "GUNNERSBURY_A", "Gunnersbury (A)"},
    {  68, "KEW_GARDENS_A", "Kew Gardens (A)"},
    {  69, "RICHMOND_A", "Richmond (A)"},
    {  70, "RICHMOND_B", "Richmond (B)"},
    {  71, "KEW_GARDENS_B", "Kew Gardens (B)"},
    {  72, "GUNNERSBURY_B", "Gunnersbury (B)"},
    {  73, "TURNHAM_GREEN_A", "Turnham Green (A)"},
    {  74, "TURNHAM_GREEN_B", "Turnham Green (B)"},
    {  75, "STAMFORD_BROOK", "Stamford Brook"},
    {  76, "RAVENSCOURT_PARK", "Ravenscourt Park"},
    {  77, "HAMMERSMITH_A", "Hammersmith (A)"},
    {  79, "WEST_KENSINGTON", "West Kensington"},
    {  80, "BARONS_COURT", "Barons Court"},
    {  81, "HAMMERSMITH_B", "Hammersmith (B)"},
    {  82, "HAMMERSMITH_C", "Hammersmith (C)"},
    {  83, "GOLDHAWK_ROAD", "Goldhawk Road"},
    {  84, "SHEPHERDS_BUSH_MARKET", "Shepherds Bush Market"},
    {  85, "WOOD_LANE", "Wood Lane"},
    {  86, "WHITE_CITY", "White City"},
    {  87, "EAST_ACTON", "East Acton"},
    {  88, "NORTH_ACTON", "North Acton"},
    {  89, "LATIMER_ROAD", "Latimer Road"},
    {  90, "LADBROKE_GROVE", "Ladbroke Grove"},
    {  91, "WESTBOURNE_PARK", "Westbourne Park"},
    {  92, "ROYAL_OAK", "Royal Oak"},
    {  93, "EDGEWARE_ROAD_A", "Edgeware Road (A)"},
    {  94, "WARWICK_AVENUE", "Warwick Avenue"},
    {  95, "MAIDA_VALE", "Maida Vale"},
    {  96, "KILBURN_PARK", "Kilburn Park"},
    {  97, "QUEENS_PARK", "Queens Park"},
    {  98, "KENSAL_GREEN", "Kensal Green"},
    {  99, "WILLESDEN_JUNCTION", "Willesden Junction"},
    { 100, "ALPERTON", "Alperton"},
    { 101, "SUDBURY_TOWN", "Sudbury Town"},
    { 102, "SUDBURY_HILL", "Sudbury Hill"},
    { 103, "SOUTH_HARROW", "South Harrow"},
    { 104, "HARLESDEN", "Harlesden"},
    { 105, "STONEBRIDGE_PARK", "Stonebridge Park"},
    { 106, "WEMBLEY_CENTRAL", "Wembley Central"},
    { 107, "NORTH_WEMBLEY", "North Wembley"},
    { 108, "SOUTH_KENTON", "South Kenton"},
    { 109, "NORTHWICK_PARK", "Northwick Park"},
    { 110, "PRESTON_ROAD", "Preston Road"},
    { 111, "KENTON", "Kenton"},
    { 112, "HARROW_WEALDSTONE", "Harrow Wealdstone"},
    { 113, "HEADSTONE_LANE", "Headstone Lane"},
    { 114, "HATCH_END", "Hatch End"},
    { 115, "CARPENDERS_PARK", "Carpenders Park"},
    { 116, "BUSHEY", "Bushey"},
    { 117, "WATFORD_HIGH_STREET", "Watford High Street"},
    { 118, "WATFORD_JUNCTION", "Watford Junction"},
    { 119, "CANONS_PARK", "Canons Park"},
    { 120, "STANMORE", "Stanmore"},
    { 121, "QUEENSBURY", "Queensbury"},
    { 122, "KINGSBURY", "Kingsbury"},
    { 123, "WEMBLEY_PARK", "Wembley Park"},
    { 125, "NEASDEN", "Neasden"},
    { 126, "DOLLIS_HILL", "Dollis Hill"},
    { 127, "WILLESDEN_GREEN", "Willesden Green"},
    { 128, "KILBURN", "Kilburn"},
    { 129, "KENSAL_RISE", "Kensal Rise"},
    { 130, "BRONDESBURY_PARK", "Brondesbury Park"},
    { 131, "BRONDESBURY", "Brondesbury"},
    { 132, "KILBURN_HIGH_ROAD", "Kilburn High Road"},
    { 133, "EDGEWARE_ROAD_B", "Edgeware Road (B)"},
    { 134, "MARYLEBONE", "Marylebone"},
    { 135, "FINCHLEY_ROAD_A", "Finchley Road (A)"},
    { 136, "FINCHLEY_ROAD_FROGNAL_A", "Finchley Road Frognal (A)"},
    { 137, "FINCHLEY_ROAD_B", "Finchley Road (B)"},
    { 138, "SWISS_COTTAGE", "Swiss Cottage"},
    { 139, "ST_JOHNS_WOOD", "St. Johns Wood"},
    { 140, "BAKER_STREET_A", "Baker Street (A)"},
    { 141, "BAKER_STREET_B", "Baker Street (B)"},
    { 142, "EDGEWARE_ROAD_C", "Edgeware Road (C)"},
    { 143, "EDGEWARE_ROAD_D", "Edgeware Road (D)"},
    { 144, "PADDINGTON", "Paddington"},
    { 145, "BAYSWATER", "Bayswater"},
    { 146, "HOLLAND_PARK", "Holland Park"},
    { 147, "SHEPHERDS_BUSH_A", "Shepherds Bush (A)"},
    { 148, "SHEPHERDS_BUSH_B", "Shepherds Bush (B)"},
    { 149, "KENSINGTON_OLYMPIA_A", "Kensington Olympia (A)"},
    { 150, "KENSINGTON_OLYMPIA_B", "Kensington Olympia (B)"},
    { 151, "EARLS_COURT_A", "Earls Court (A)"},
    { 152, "EARLS_COURT_B", "Earls Court (B)"},
    { 153, "WEST_BROMPTON_A", "West Brompton (A)"},
    { 154, "WEST_BROMPTON_B", "West Brompton (B)"},
    { 155, "FULHAM_BROADWAY", "Fulham Broadway"},
    { 156, "PARSONS_GREEN", "Parsons Green"},
    { 157, "PUTNEY_BRIDGE", "Putney Bridge"},
    { 158, "EAST_PUTNEY", "East Putney"},
    { 159, "SOUTHFIELDS", "Southfields"},
    { 160, "WIMBLEDON_PARK_A", "Wimbledon Park (A)"},
    { 161, "WIMBLEDON_A", "Wimbledon (A)"},
    { 162, "WIMBLEDON_PARK_B", "Wimbledon Park (B)"},
    { 163, "WIMBLEDON_CHASE", "Wimbledon Chase"},
    { 164, "SOUTH_MERTON", "South Merton"},
    { 165, "MORDEN_SOUTH", "Morden South"},
    { 166, "ST_HELIER", "St. Helier"},
    { 167, "SUTTON_COMMON", "Sutton Common"},
    { 168, "WEST_SUTTON", "West Sutton"},
    { 169, "SUTTON_", "Sutton"},
    { 170, "CARSHALTON", "Carshalton"},
    { 171, "HACKBRIDGE", "Hackbridge"},
    { 172, "MITCHAM_JUNCTION_A", "Mitcham Junction (A)"},
    { 173, "MITCHAM_JUNCTION_B", "Mitcham Junction (B)"},
    { 174, "MITCHAM", "Mitcham"},
    { 175, "BELGRAVE_WALK", "Belgrave Walk"},
    { 176, "PHIPPS_BRIDGE", "Phipps Bridge"},
    { 177, "MORDEN_ROAD", "Morden Road"},
    { 178, "MORDEN", "Morden"},
    { 179, "SOUTH_WIMBLEDON", "South Wimbledon"},
    { 180, "COLLIERS_WOOD", "Colliers Wood"},
    { 181, "MERTON_PARK", "Merton Park"},
    { 182, "DUNDONALD_ROAD", "Dundonald Road"},
    { 183, "WIMBLEDON_B", "Wimbledon (B)"},
    { 184, "HAYDONS_ROAD", "Haydons Road"},
    { 185, "TOOTING_BROADWAY", "Tooting Broadway"},
    { 186, "TOOTING_BEC", "Tooting Bec"},
    { 187, "BALHAM", "Balham"},
    { 188, "CLAPHAM_SOUTH", "Clapham South"},
    { 189, "CLAPHAM_COMMON", "Clapham Common"},
    { 190, "CLAPHAM_NORTH", "Clapham North"},
    { 191, "BRIXTON", "Brixton"},
    { 192, "TOOTING", "Tooting"},
    { 193, "MITCHAM_EASTFIELDS", "Mitcham Eastfields"},
    { 194, "STREATHAM", "Streatham"},
    { 195, "TULSE_HILL", "Tulse Hill"},
    { 196, "HERNE_HILL", "Herne Hill"},
    { 197, "LOUGHBOROUGH_JUNCTION", "Loughborough Junction"},
    { 198, "OVAL", "Oval"},
    { 199, "KENNINGTON_A", "Kennington (A)"},
    { 200, "KENNINGTON_B", "Kennington (B)"},
    { 201, "STOCKWELL", "Stockwell"},
    { 202, "CLAPHAM_HIGH_STREET", "Clapham High Street"},
    { 203, "WANDSWORTH_ROAD", "Wandsworth Road"},
    { 204, "CLAPHAM_JUNCTION_A", "Clapham Junction (A)"},
    { 205, "CLAPHAM_JUNCTION_B", "Clapham Junction (B)"},
    { 206, "IMPERIAL_WHARF_", "Imperial Wharf"},
    { 207, "BATTERSEA_POWER_STATION", "Battersea Power Station"},
    { 208, "NINE_ELMS", "Nine Elms"},
    { 209, "VAUXHALL", "Vauxhall"},
    { 210, "PIMLICO", "Pimlico"},
    { 211, "GLOUCESTER_ROAD_A", "Gloucester Road (A)"},
    { 212, "GLOUCESTER_ROAD_B", "Gloucester Road (B)"},
    { 213, "SOUTH_KENSINGTON_A", "South Kensington (A)"},
    { 214, "SOUTH_KENSINGTON_B", "South Kensington (B)"},
    { 215, "SLOANE_SQUARE", "Sloane Square"},
    { 216, "VICTORIA_A", "Victoria (A)"},
    { 217, "VICTORIA_B", "Victoria (B)"},
    { 218, "ST_JAMESS_PARK", "St. Jamess Park"},
    { 219, "WESTMINSTER_A", "Westminster (A)"},
    { 220, "WESTMINSTER_B", "Westminster (B)"},
    { 221, "EMBANKMENT_A", "Embankment (A)"},
    { 222, "EMBANKMENT_B", "Embankment (B)"},
    { 223, "CHARING_CROSS", "Charing Cross"},
    { 224, "LEICESTER_SQUARE", "Leicester Square"},
    { 225, "PICCADILLY_CIRCUS", "Piccadilly Circus"},
    { 226, "GREEN_PARK", "Green Park"},
    { 227, "HYDE_PARK_CORNER", "Hyde Park Corner"},
    { 228, "KNIGHTSBRIDGE", "Knightsbridge"},
    { 229, "QUEENSWAY", "Queensway"},
    { 230, "LANCASTER_GATE", "Lancaster Gate"},
    { 231, "MARBLE_ARCH", "Marble Arch"},
    { 232, "BOND_STREET_A", "Bond Street (A)"},
    { 233, "BOND_STREET_B", "Bond Street (B)"},
    { 234, "OXFORD_CIRCUS", "Oxford Circus"},
    { 235, "TOTTENHAM_COURT_ROAD_A", "Tottenham Court Road (A)"},
    { 236, "TOTTENHAM_COURT_ROAD_B", "Tottenham Court Road (B)"},
    { 237, "GOODGE_STREET", "Goodge Street"},
    { 238, "WARREN_STREET", "Warren Street"},
    { 239, "REGENTS_PARK", "Regents Park"},
    { 240, "GREAT_PORTLAND_STREET", "Great Portland Street"},
    { 241, "EUSTON_A", "Euston (A)"},
    { 242, "EUSTON_B", "Euston (B)"},
    { 243, "EUSTON_C", "Euston (C)"},
    { 244, "EUSTON_D", "Euston (D)"},
    { 245, "KINGS_CROSS_ST_PANCRAS_A", "Kings Cross St. Pancras (A)"},
    { 246, "KINGS_CROSS_ST_PANCRAS_B", "Kings Cross St. Pancras (B)"},
    { 247, "MORNINGTON_CRESCENT", "Mornington Crescent"},
    { 248, "CAMDEN_TOWN", "Camden Town"},
    { 249, "CHALK_FARM", "Chalk Farm"},
    { 250, "BELSIZE_PARK", "Belsize Park"},
    { 251, "HAMPSTEAD_HEATH", "Hampstead Heath"},
    { 252, "FINCHLEY_ROAD_FROGNAL_B", "Finchley Road Frognal (B)"},
    { 253, "WEST_HAMPSTEAD", "West Hampstead"},
    { 254, "WEST_HAMPSTEAD_THAMESLINK", "West Hampstead Thameslink"},
    { 255, "CRICKLEWOOD", "Cricklewood"},
    { 256, "BRENT_CROSS_WEST", "Brent Cross West"},
    { 257, "HENDON", "Hendon"},
    { 258, "COLINDALE", "Colindale"},
    { 259, "BURNT_OAK", "Burnt Oak"},
    { 260, "EDGEWARE", "Edgeware"},
    { 261, "MILL_HILL_BROADWAY", "Mill Hill Broadway"},
    { 262, "ELSTREE_BOREHAMWOOD", "Elstree Borehamwood"},
    { 264, "HENDON_CENTRAL", "Hendon Central"},
    { 265, "BRENT_CROSS", "Brent Cross"},
    { 266, "GOLDERS_GREEN", "Golders Green"},
    { 267, "HAMPSTEAD", "Hampstead"},
    { 268, "GOSPEL_OAK_A", "Gospel Oak (A)"},
    { 269, "GOSPEL_OAK_B", "Gospel Oak (B)"},
    { 270, "KENTISH_TOWN_WEST", "Kentish Town West"},
    { 271, "CAMDEN_ROAD", "Camden Road"},
    { 272, "ANGEL", "Angel"},
    { 273, "RUSSELL_SQUARE_A", "Russell Square (A)"},
    { 274, "RUSSELL_SQUARE_B", "Russell Square (B)"},
    { 275, "HOLBORN", "Holborn"},
    { 276, "COVENT_GARDEN", "Covent Garden"},
    { 277, "CHANCERY_LANE", "Chancery Lane"},
    { 278, "CITY_THAMESLINK", "City Thameslink"},
    { 279, "ST_PAULS", "St. Pauls"},
    { 280, "BANK_A", "Bank (A)"},
    { 281, "BANK_B", "Bank (B)"},
    { 282, "MANSION_HOUSE", "Mansion House"},
    { 283, "BLACKFRIARS", "Blackfriars"},
    { 284, "TEMPLE", "Temple"},
    { 286, "SOUTHWARK", "Southwark"},
    { 288, "LAMBETH_NORTH", "Lambeth North"},
    { 289, "ELEPHANT_CASTLE_A", "Elephant Castle (A)"},
    { 290, "ELEPHANT_CASTLE_B", "Elephant Castle (B)"},
    { 291, "DENMARK_HILL_A", "Denmark Hill (A)"},
    { 292, "DENMARK_HILL_B", "Denmark Hill (B)"},
    { 293, "PECKHAM_RYE", "Peckham Rye"},
    { 294, "QUEENS_ROAD_PECKHAM", "Queens Road Peckham"},
    { 295, "BEDDINGTON_LANE", "Beddington Lane"},
    { 296, "THERAPIA_LANE", "Therapia Lane"},
    { 297, "AMPERE_WAY", "Ampere Way"},
    { 298, "WADDON_MARSH", "Waddon Marsh"},
    { 299, "WANDLE_PARK", "Wandle Park"},
    { 300, "REEVES_CORNER", "Reeves Corner"},
    { 301, "CENTRALE", "Centrale"},
    { 302, "WEST_CROYDON_A", "West Croydon (A)"},
    { 303, "WEST_CROYDON_B", "West Croydon (B)"},
    { 304, "WELLESLEY_ROAD", "Wellesley Road"},
    { 305, "GEORGE_STREET", "George Street"},
    { 306, "CHURCH_STREET", "Church Street"},
    { 307, "COULSDON_SOUTH", "Coulsdon South"},
    { 309, "PURLEY", "Purley"},
    { 310, "SOUTH_CROYDON", "South Croydon"},
    { 311, "EAST_CROYDON_A", "East Croydon (A)"},
    { 312, "EAST_CROYDON_B", "East Croydon (B)"},
    { 313, "NORTHWOOD_JUNCTION", "Northwood Junction"},
    { 314, "CRYSTAL_PALACE", "Crystal Palace"},
    { 315, "ANERLEY", "Anerley"},
    { 316, "PENGE_WEST", "Penge West"},
    { 317, "SYDENHAM", "Sydenham"},
    { 318, "FOREST_HILL", "Forest Hill"},
    { 319, "HONOR_OAK_PARK", "Honor Oak Park"},
    { 320, "BROCKLEY", "Brockley"},
    { 321, "NUNHEAD", "Nunhead"},
    { 322, "NEW_CROSS_GATE", "New Cross Gate"},
    { 324, "SURREY_QUAYS", "Surrey Quays"},
    { 325, "CANADA_WATER", "Canada Water"},
    { 326, "ROTHERHITHE", "Rotherhithe"},
    { 327, "BERMONDSEY", "Bermondsey"},
    { 328, "BOROUGH", "Borough"},
    { 329, "LONDON_BRIDGE_A", "London Bridge (A)"},
    { 330, "LONDON_BRIDGE_B", "London Bridge (B)"},
    { 331, "TOWER_HILL", "Tower Hill"},
    { 332, "TOWER_GATEWAY", "Tower Gateway"},
    { 333, "WAPPING", "Wapping"},
    { 334, "SHADWELL_A", "Shadwell (A)"},
    { 335, "LIMEHOUSE", "Limehouse"},
    { 336, "WESTFERRY", "Westferry"},
    { 337, "SHADWELL_B", "Shadwell (B)"},
    { 338, "ALDGATE", "Aldgate"},
    { 339, "MOORGATE", "Moorgate"},
    { 340, "OLD_STREET", "Old Street"},
    { 342, "LIVERPOOL_STREET_A", "Liverpool Street (A)"},
    { 343, "ALDGATE_EAST", "Aldgate East"},
    { 344, "WHITECHAPEL_A", "Whitechapel (A)"},
    { 345, "WHITECHAPEL_B", "Whitechapel (B)"},
    { 346, "BETHNAL_GREEN_CENTRAL_LINE", "Bethnal Green Central Line"},
    { 347, "STEPNEY_GREEN", "Stepney Green"},
    { 348, "MILE_END", "Mile End"},
    { 349, "SHOREDITCH_HIGH_STREET", "Shoreditch High Street"},
    { 350, "BETHNAL_GREEN_WEAVER_LINE", "Bethnal Green Weaver Line"},
    { 351, "CAMBRIDGE_HEATH", "Cambridge Heath"},
    { 352, "LONDON_FIELDS", "London Fields"},
    { 353, "HOXTON", "Hoxton"},
    { 354, "HAGGERSTON", "Haggerston"},
    { 355, "DALSTON_JUNCTION", "Dalston Junction"},
    { 356, "CANONBURY", "Canonbury"},
    { 357, "HIGHBURY_ISLINGTON_A", "Highbury Islington (A)"},
    { 359, "DALSTON_KINGSLAND", "Dalston Kingsland"},
    { 360, "HIGHBURY_ISLINGTON_B", "Highbury Islington (B)"},
    { 361, "CALEDONIAN_ROAD_BARNSBURY", "Caledonian Road Barnsbury"},
    { 362, "CALEDONIAN_ROAD", "Caledonian Road"},
    { 363, "HOLLOWAY_ROAD", "Holloway Road"},
    { 364, "ARSENAL", "Arsenal"},
    { 365, "FINSBURY_PARK_A", "Finsbury Park (A)"},
    { 366, "FINSBURY_PARK_B", "Finsbury Park (B)"},
    { 367, "MANOR_HOUSE", "Manor House"},
    { 368, "CROUCH_HILL", "Crouch Hill"},
    { 369, "KENTISH_TOWN", "Kentish Town"},
    { 370, "TUFNELL_PARK", "Tufnell Park"},
    { 371, "UPPER_HOLLOWAY", "Upper Holloway"},
    { 372, "ARCHWAY", "Archway"},
    { 373, "HIGHGATE", "Highgate"},
    { 374, "EAST_FINCHLEY", "East Finchley"},
    { 375, "FINCHLEY_CENTRAL", "Finchley Central"},
    { 376, "MILL_HILL_EAST", "Mill Hill East"},
    { 377, "WEST_FINCHLEY", "West Finchley"},
    { 378, "WOODSIDE_PARK", "Woodside Park"},
    { 379, "TOTTERIDGE_WHETSTONE", "Totteridge Whetstone"},
    { 380, "HIGH_BARNET", "High Barnet"},
    { 381, "OAKLEIGH_PARK", "Oakleigh Park"},
    { 384, "NEW_SOUTHGATE", "New Southgate"},
    { 385, "HARRINGAY_GREEN_LANES", "Harringay Green Lanes"},
    { 386, "TURNPIKE_LANE", "Turnpike Lane"},
    { 387, "WOOD_GREEN", "Wood Green"},
    { 388, "BOUNDS_GREEN", "Bounds Green"},
    { 389, "ARNOS_GROVE", "Arnos Grove"},
    { 390, "SOUTHGATE", "Southgate"},
    { 391, "OAKWOOD", "Oakwood"},
    { 392, "COCKFOSTERS", "Cockfosters"},
    { 393, "CHESHUNT", "Cheshunt"},
    { 394, "THEOBALDS_GROVE", "Theobalds Grove"},
    { 395, "TURKEY_STREET", "Turkey Street"},
    { 396, "SOUTHBURY", "Southbury"},
    { 397, "ENFIELD_TOWN", "Enfield Town"},
    { 398, "BUSH_HILL_PARK", "Bush Hill Park"},
    { 399, "EDMONTON_GREEN", "Edmonton Green"},
    { 400, "SILVER_STREET", "Silver Street"},
    { 401, "WHITE_HART_LANE", "White Hart Lane"},
    { 402, "BRUCE_GROVE", "Bruce Grove"},
    { 403, "SEVEN_SISTERS", "Seven Sisters"},
    { 404, "STAMFORD_HILL", "Stamford Hill"},
    { 405, "STOKE_NEWINGTON", "Stoke Newington"},
    { 406, "RECTORY_ROAD", "Rectory Road"},
    { 407, "HACKNEY_DOWNS_A", "Hackney Downs (A)"},
    { 408, "HACKNEY_DOWNS_B", "Hackney Downs (B)"},
    { 409, "HACKNEY_CENTRAL", "Hackney Central"},
    { 410, "HOMERTON", "Homerton"},
    { 411, "HACKNEY_WICK", "Hackney Wick"},
    { 412, "STRATFORD", "Stratford"},
    { 413, "PUDDING_MILL_LANE", "Pudding Mill Lane"},
    { 414, "BOW_CHURCH", "Bow Church"},
    { 415, "DEVONS_ROAD", "Devons Road"},
    { 416, "LANGDON_PARK", "Langdon Park"},
    { 417, "ALL_SAINTS", "All Saints"},
    { 418, "POPLAR", "Poplar"},
    { 419, "WEST_INDIA_QUAY_A", "West India Quay (A)"},
    { 420, "WEST_INDIA_QUAY_B", "West India Quay (B)"},
    { 421, "CANARY_WHARF_A", "Canary Wharf (A)"},
    { 422, "CANARY_WHARF_B", "Canary Wharf (B)"},
    { 423, "HERON_QUAYS", "Heron Quays"},
    { 424, "SOUTH_QUAY", "South Quay"},
    { 425, "CROSSHARBOUR", "Crossharbour"},
    { 426, "MUDCHUTE", "Mudchute"},
    { 427, "ISLAND_GARDENS", "Island Gardens"},
    { 428, "CUTTY_SARK_FOR_MARITIME_GREENWICH", "Cutty Sark for Maritime Greenwich"},
    { 429, "DEPTFORD", "Deptford"},
    { 430, "GREENWICH_A", "Greenwich (A)"},
    { 431, "GREENWICH_B", "Greenwich (B)"},
    { 432, "DEPTFORD_BRIDGE", "Deptford Bridge"},
    { 433, "ELVERSON_ROAD", "Elverson Road"},
    { 434, "LEWISHAM", "Lewisham"},
    { 435, "CROFTON_PARK", "Crofton Park"},
    { 436, "CATFORD", "Catford"},
    { 437, "BELLINGHAM", "Bellingham"},
    { 438, "LEBANON_ROAD", "Lebanon Road"},
    { 439, "SANDILANDS", "Sandilands"},
    { 440, "LLOYD_PARK", "Lloyd Park"},
    { 441, "COOMBE_LANE", "Coombe Lane"},
    { 442, "GRAVEL_HILL", "Gravel Hill"},
    { 443, "ADDINGTON_VILLAGE", "Addington Village"},
    { 444, "FIELDWAY", "Fieldway"},
    { 445, "KING_HENRYS_DRIVE", "King Henrys Drive"},
    { 446, "NEW_ADDINGTON", "New Addington"},
    { 447, "ADDISCOMBE", "Addiscombe"},
    { 448, "BLACKHORSE_LANE", "Blackhorse Lane"},
    { 449, "WOODSIDE", "Woodside"},
    { 450, "ARENA", "Arena"},
    { 451, "ELMERS_END", "Elmers End"},
    { 452, "HARRINGTON_ROAD", "Harrington Road"},
    { 453, "BIRKBECK", "Birkbeck"},
    { 454, "AVENUE_ROAD", "Avenue Road"},
    { 455, "BECKENHAM_ROAD", "Beckenham Road"},
    { 456, "BECKENHAM_JUNCTION", "Beckenham Junction"},
    { 457, "ORPINGTON_", "Orpington"},
    { 458, "DARTFORD", "Dartford"},
    { 460, "ST_MARY_CRAY", "St. Mary Cray"},
    { 461, "PETTS_WOOD", "Petts Wood"},
    { 462, "BICKLEY", "Bickley"},
    { 463, "BROMLEY_SOUTH", "Bromley South"},
    { 464, "SHORTLANDS", "Shortlands"},
    { 465, "RAVENSBOURNE", "Ravensbourne"},
    { 466, "BECKENHAM_HILL", "Beckenham Hill"},
    { 467, "MAZE_HILL", "Maze Hill"},
    { 468, "NORTH_GREENWICH", "North Greenwich"},
    { 469, "IFS_CLOUD_GREENWICH_PENINSULA", "Ifs Cloud Greenwich Peninsula"},
    { 470, "WESTCOMBE_PARK", "Westcombe Park"},
    { 471, "CHARLTON", "Charlton"},
    { 472, "WOOLWICH_ARSENAL_A", "Woolwich Arsenal (A)"},
    { 473, "WOOLWICH_ARSENAL_B", "Woolwich Arsenal (B)"},
    { 474, "WOOLWICH", "Woolwich"},
    { 475, "PLUMSTEAD_", "Plumstead"},
    { 476, "ABBEY_WOOD", "Abbey Wood"},
    { 477, "SLADE_GREEN_", "Slade Green"},
    { 479, "SWANLEY_", "Swanley"},
    { 480, "BECKTON", "Beckton"},
    { 481, "GALLIONS_REACH", "Gallions Reach"},
    { 482, "CYPRUS", "Cyprus"},
    { 483, "BECKTON_PARK", "Beckton Park"},
    { 484, "ROYAL_ALBERT", "Royal Albert"},
    { 485, "PRINCE_REGENT", "Prince Regent"},
    { 486, "CUSTOM_HOUSE_FOR_EXCEL_A", "Custom House for Excel (A)"},
    { 487, "CUSTOM_HOUSE_FOR_EXCEL_B", "Custom House for Excel (B)"},
    { 488, "KING_GEORGE_V", "King George (V)"},
    { 489, "LONDON_CITY_AIRPORT", "London City Airport"},
    { 490, "PONTOON_DOCK", "Pontoon Dock"},
    { 491, "WEST_SILVERTOWN", "West Silvertown"},
    { 492, "IFS_CLOUD_ROYAL_DOCKS", "Ifs Cloud Royal Docks"},
    { 493, "ROYAL_VICTORIA", "Royal Victoria"},
    { 494, "CANNING_TOWN_A", "Canning Town (A)"},
    { 495, "CANNING_TOWN_B", "Canning Town (B)"},
    { 496, "EAST_INDIA", "East India"},
    { 497, "BLACKWALL", "Blackwall"},
    { 498, "BROMLEY_BY_BOW", "Bromley By Bow"},
    { 499, "WEST_HAM_A", "West Ham (A)"},
    { 500, "WEST_HAM_B", "West Ham (B)"},
    { 501, "STAR_LANE", "Star Lane"},
    { 502, "PLAISTOW", "Plaistow"},
    { 503, "UPTON_PARK", "Upton Park"},
    { 504, "EAST_HAM", "East Ham"},
    { 505, "BARKING_A", "Barking (A)"},
    { 506, "BARKING_B", "Barking (B)"},
    { 507, "BARKING_RIVERSIDE", "Barking Riverside"},
    { 508, "UPNEY", "Upney"},
    { 509, "BECONTREE", "Becontree"},
    { 510, "DAGENHAM_HEATHWAY", "Dagenham Heathway"},
    { 511, "DAGENHAM_EAST", "Dagenham East"},
    { 512, "ELM_PARK", "Elm Park"},
    { 513, "HORNCHURCH", "Hornchurch"},
    { 514, "UPMINSTER_BRIDGE", "Upminster Bridge"},
    { 515, "UPMINSTER_A", "Upminster (A)"},
    { 516, "UPMINSTER_B", "Upminster (B)"},
    { 517, "EMERSON_PARK", "Emerson Park"},
    { 518, "SHENFIELD", "Shenfield"},
    { 519, "BRENTWOOD", "Brentwood"},
    { 520, "HAROLD_WOOD", "Harold Wood"},
    { 521, "GIDEA_PARK", "Gidea Park"},
    { 522, "ROMFORD", "Romford"},
    { 523, "CHADWELL_HEATH", "Chadwell Heath"},
    { 524, "GOODMAYES", "Goodmayes"},
    { 525, "SEVEN_KINGS", "Seven Kings"},
    { 526, "ILFORD", "Ilford"},
    { 527, "MANOR_PARK", "Manor Park"},
    { 528, "FOREST_GATE", "Forest Gate"},
    { 529, "WANSTEAD_PARK", "Wanstead Park"},
    { 530, "WOODGRANGE_PARK", "Woodgrange Park"},
    { 531, "ABBEY_ROAD", "Abbey Road"},
    { 532, "STRATFORD_HIGH_STREET", "Stratford High Street"},
    { 533, "MARYLAND", "Maryland"},
    { 534, "LEYTON", "Leyton"},
    { 535, "STRATFORD_INTERNATIONAL", "Stratford International"},
    { 536, "CLAPTON", "Clapton"},
    { 537, "ST_JAMES_STREET", "St. James Street"},
    { 538, "TOTTENHAM_HALE", "Tottenham Hale"},
    { 539, "SOUTH_TOTTENHAM", "South Tottenham"},
    { 540, "BLACKHORSE_ROAD_A", "Blackhorse Road (A)"},
    { 541, "BLACKHORSE_ROAD_B", "Blackhorse Road (B)"},
    { 542, "CHINGFORD", "Chingford"},
    { 543, "HIGHAMS_PARK", "Highams Park"},
    { 544, "WOOD_STREET", "Wood Street"},
    { 545, "WALTHAMSTOW_CENTRAL_A", "Walthamstow Central (A)"},
    { 546, "WALTHAMSTOW_CENTRAL_B", "Walthamstow Central (B)"},
    { 547, "WALTHAMSTOW_QUEENS_ROAD", "Walthamstow Queens Road"},
    { 548, "LEYTON_MIDLAND_ROAD", "Leyton Midland Road"},
    { 549, "LEYTONSTONE_HIGH_ROAD", "Leytonstone High Road"},
    { 550, "LEYTONSTONE", "Leytonstone"},
    { 551, "WANSTEAD", "Wanstead"},
    { 552, "REDBRIDGE", "Redbridge"},
    { 553, "GANTS_HILL", "Gants Hill"},
    { 554, "NEWBURY_PARK", "Newbury Park"},
    { 555, "BARKINGSIDE", "Barkingside"},
    { 556, "FAIRLOP", "Fairlop"},
    { 557, "HAINAULT", "Hainault"},
    { 558, "GRANGE_HILL", "Grange Hill"},
    { 559, "CHIGWELL", "Chigwell"},
    { 560, "RODING_VALLEY", "Roding Valley"},
    { 561, "SNARESBROOK", "Snaresbrook"},
    { 562, "SOUTH_WOODFORD", "South Woodford"},
    { 563, "WOODFORD", "Woodford"},
    { 564, "BUCKHURST_HILL", "Buckhurst Hill"},
    { 565, "LOUGHTON", "Loughton"},
    { 566, "DEBDEN", "Debden"},
    { 567, "THEYDON_BOIS", "Theydon Bois"},
    { 568, "EPPING", "Epping"},
};

static const uint16_t kStationNameCount = 552;

// Binary-search lookup.  Returns nullptr if ledIndex is not found.
inline const StationNameEntry* findStationEntry(uint16_t ledIndex) {
    int lo = 0, hi = static_cast<int>(kStationNameCount) - 1;
    while (lo <= hi) {
        int mid = lo + (hi - lo) / 2;
        if (kStationNames[mid].led == ledIndex) return &kStationNames[mid];
        if (kStationNames[mid].led < ledIndex)  lo = mid + 1;
        else                                     hi = mid - 1;
    }
    return nullptr;
}

// Convenience wrappers.
inline const char* getStationHumanName(uint16_t led) {
    const StationNameEntry* e = findStationEntry(led);
    return e ? e->humanName : nullptr;
}
inline const char* getStationConstName(uint16_t led) {
    const StationNameEntry* e = findStationEntry(led);
    return e ? e->constName : nullptr;
}

